backend:
  name: git-gateway
  branch: master

media_folder: src/img
public_folder: static/img

#media_library:
  #name: cloudinary
  #config:
    #cloud_name: cloudimgts
    #api_key: 739913194731388

collections:
  - name: "blog"
    label: "skriva"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
