[Settings]
# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.

[build]
  # This is the directory to change to before starting a build.
  base    = "project/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "project/build-output/"
  # This will be your default build command
  command = "echo 'default context'"
  # This is where we will look for your lambda functions
  functions = "project/functions/"
  # Ignore build command if exit 0
  ignore = "git diff --quiet HEAD^ HEAD sub_dir/"
  # If skip_processing = true, all other settings are ignored
  [build.processing]
    skip_processing = false
  [build.processing.css]
    bundle = true
    minify = false
  [build.processing.js]
    bundle = true
    minify = false
  [build.processing.html]
    pretty_urls = true
  [build.processing.images]
    compress = true

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src https:"
    # Multi-key header rules are expressed with multi-line strings
    Link = '''
    </assets/css/base.css>; rel=preload; as=style, \
    </assets/css/base2.css>; rel=preload; as=style, \
    </assets/css/base3.css>; rel=preload; as=style'''
    # Basic-Auth allows you to password protect your whole site but is only available
    # to paid accounts
    Basic-Auth = "someuser:somepassword anotheruser:anotherpassword"
